In [19]:
from anchor import utils
from anchor import anchor_tabular
import pandas as pd
import sklearn.ensemble
import numpy as np
from anchor import anchor_tabular
import os

In [20]:
dataset_folder = '../../datasets/'
dataset = utils.load_dataset('lending', balance=True, dataset_folder=dataset_folder, discretize=True)
print(dataset.train[0])

[1. 0. 3. 0. 0. 3. 0. 0. 1.]


In [21]:
c = sklearn.ensemble.RandomForestClassifier(n_estimators=50, n_jobs=5)
c.fit(dataset.train, dataset.labels_train)
#print(np.unique(dataset.labels_train))
print('Train', sklearn.metrics.accuracy_score(dataset.labels_train, c.predict(dataset.train)))
print('Test', sklearn.metrics.accuracy_score(dataset.labels_test, c.predict(dataset.test)))

Train 0.9124586549062844
Test 0.828042328042328


In [29]:
transformed_data = []

for r in dataset.train:
    transformed_data.append([dataset.categorical_names[i][int(r_)] for i, r_ in enumerate(r)])        

print(transformed_data[0])

train_data = pd.DataFrame(transformed_data, columns=dataset.feature_names)
print(train_data.shape)
nb_vals = 800

print(dataset.train[0])
print(dataset.train[0].reshape(1, -1))
y=[]
for k in range(0, nb_vals):
    y.append(c.predict(dataset.train[k].reshape(1, -1))[0])


['5400.00 < loan_amnt <= 10000.00', 'MORTGAGE', 'annual_inc > 82000.00', 'desc <= 4.00', 'inq_last_6mths <= 0.00', 'revol_util > 72.22', 'last_fico_range_high <= 649.00', 'last_fico_range_low <= 645.00', '0']
(9070, 9)
[1. 0. 3. 0. 0. 3. 0. 0. 1.]
[[1. 0. 3. 0. 0. 3. 0. 0. 1.]]


In [30]:
import sys
sys.path.append(sys.path[0] + '/..')

import arg_explainer as ae
from importlib import reload
reload(ae)
import arg_explainer as ae

print(dataset.feature_names)
explainer = ae.ArgTabularExplainer(c, train_data.iloc[0:nb_vals], y, 'lending_' + str(nb_vals), compute=True, output_path='../saves')

['loan_amnt', 'home_ownership', 'annual_inc', 'desc', 'inq_last_6mths', 'revol_util', 'last_fico_range_high', 'last_fico_range_low', 'pub_rec_bankruptcies']
Generating arguments
len  1 : 0 ,  1
34 potential arg checked ( 0 not minimal)
len  2 : 54 ,  4
469 potential arg checked ( 12 not minimal)
len  3 : 212 ,  200
2800 potential arg checked ( 832 not minimal)
len  4 : 646 ,  998
7835 potential arg checked ( 6621 not minimal)
len  5 : 432 ,  524
8076 potential arg checked ( 21455 not minimal)
len  6 : 39 ,  5
3895 potential arg checked ( 28163 not minimal)
len  7 : 2 ,  0
1015 potential arg checked ( 17774 not minimal)
len  8 : 0 ,  0
110 potential arg checked ( 5585 not minimal)
len  9 : 0 ,  0
0 potential arg checked ( 705 not minimal)
Saving to  ../saves\lending_800_minimals.df


In [31]:
G = explainer.build_attack_graph(compute=True, display_graph=False)
print('edges per node:', np.mean([len(G.edges(n)) for n in G.nodes()]))

explainer.export_graph('asp', '../saves')

1385 1732  args total
lending_800
edges per node: 960.1937760667308


In [32]:
explainer.af_analysis()

['lending_1000_atk_graph.df', 'lending_100_atk_graph.df', 'lending_200_atk_graph.df', 'lending_300_atk_graph.df', 'lending_500_atk_graph.df', 'lending_800_atk_graph.df'] ['lending_1000_R_atk.df', 'lending_100_R_atk.df', 'lending_200_R_atk.df', 'lending_300_R_atk.df', 'lending_500_R_atk.df', 'lending_800_R_atk.df']
[1874015, 55972, 268742, 454307, 831357, 1496462]


In [23]:
#ext_gen = explainer.extension_generator_from_graph()
ext_gen = explainer.extension_generator_from_sat(file='../saves/lending_100_sat.txt')
max_covi_ext = explainer.make_selection('max_covi', ext_gen)

Using pre-processed file...
Reading ../saves/lending_100_sat_preprocessed.txt
Time for selection:  112.84400844573975
Len max_cov_exts:  1


In [24]:
#sel = explainer.make_selection(max_covi_ext, 'max_covc')
res = explainer.apply_inference(max_covi_ext, 'universal')
#print(res)

explainer.display_explanations()

id: 0 coverage: 36 Arg 1/4: frozenset({'desc_desc <= 4.00', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 1 coverage: 26 Arg 1/3: frozenset({'revol_util_revol_util <= 25.20', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 2 coverage: 39 Arg 1/4: frozenset({'inq_last_6mths_inq_last_6mths > 1.00', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 3 coverage: 17 Arg 1/1: frozenset({'last_fico_range_high_699.00 < last_fico_range_high <= 749.00'})
id: 4 coverage: 10 Arg 1/2: frozenset({'desc_desc <= 4.00', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 5 coverage: 14 Arg 1/3: frozenset({'desc_145.00 < desc <= 392.00', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 6 coverage: 0 Arg 1/0: None
id: 7 coverage: 17 Arg 1/1: frozenset({'last_fico_range_high_699.00 < last_fico_range_high <= 749.00'})
id: 8 coverage: 3 Arg 1/1: frozenset({'revol_util_revol_util > 72.22', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 9 coverag

In [25]:
res_one = explainer.apply_inference(max_covi_ext, 'one')
print(len(res_one))
explainer.display_explanations()

31
id: 0 coverage: 36 Arg 1/4: frozenset({'desc_desc <= 4.00', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 1 coverage: 26 Arg 1/3: frozenset({'revol_util_revol_util <= 25.20', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 2 coverage: 39 Arg 1/4: frozenset({'inq_last_6mths_inq_last_6mths > 1.00', 'last_fico_range_high_last_fico_range_high <= 649.00'})
id: 3 coverage: 17 Arg 1/1: frozenset({'last_fico_range_high_699.00 < last_fico_range_high <= 749.00'})
id: 4 coverage: 10 Arg 1/2: frozenset({'desc_desc <= 4.00', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 5 coverage: 14 Arg 1/3: frozenset({'desc_145.00 < desc <= 392.00', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 6 coverage: 0 Arg 1/0: None
id: 7 coverage: 17 Arg 1/1: frozenset({'last_fico_range_high_699.00 < last_fico_range_high <= 749.00'})
id: 8 coverage: 3 Arg 1/1: frozenset({'revol_util_revol_util > 72.22', 'last_fico_range_high_last_fico_range_high > 749.00'})
id: 9 cove

## Sat solver: ASPARTIX

In [ ]:
ext_gen = explainer.extension_generator(file='asp_test.txt')
max_covi_ext = explainer.make_selection(ext_gen, 'max_covi')

In [ ]:
explainer.set_strategy('max_covc', 'existence')
## Define strategy before calling explainer.explain()
explainer.display_explanations()

0.4019384124647283
Number of extensions: 1326480
Time spent on naive extensions: 55.99906277656555 s ( 86.23851943016052 )
len(max_cov_exts)= 1326478 / 1326480
Covc strategy's coverage: 2
Top 5 covs: [2, 2, 2, 2, 2]
id: 0 coverage: 1 Arg 1/12: frozenset({'Relationship_Husband', 'Country_United-States', 'Education_Some-college'})
id: 1 coverage: 1 Arg 1/10: frozenset({'Marital Status_Never-married', 'Age_37.00 < Age <= 48.00'})
id: 2 coverage: 1 Arg 1/22: frozenset({'Age_Age > 48.00', 'Occupation_Exec-managerial', 'Capital Gain_0', 'Workclass_Private'})
id: 3 coverage: 1 Arg 1/18: frozenset({'Hours per week_Hours per week <= 40.00', 'Occupation_Machine-op-inspct'})
id: 4 coverage: 1 Arg 1/17: frozenset({'Capital Loss_0', 'Capital Gain_0', 'Occupation_Sales', 'Hours per week_Hours per week <= 40.00', 'Relationship_Husband'})
id: 5 coverage: 1 Arg 1/8: frozenset({'Occupation_Farming-fishing', 'Hours per week_Hours per week <= 40.00'})
id: 6 coverage: 1 Arg 1/24: frozenset({'Education_Bach

In [ ]:
explainer.set_strategy('max_covc', 'universal')
## Define strategy before calling explainer.explain()
explainer.display_explanations()

0.40616693248272195
Number of extensions: 521076
len(max_cov_exts)= 521074 / 521076
Covc strategy's coverage: 2
Top 5 covs: [2, 2, 2, 2, 2]
id: 0 coverage: 0 Arg 1/0: None
id: 1 coverage: 0 Arg 1/0: None
id: 2 coverage: 0 Arg 1/0: None
id: 3 coverage: 0 Arg 1/0: None
id: 4 coverage: 0 Arg 1/0: None
id: 5 coverage: 0 Arg 1/0: None
id: 6 coverage: 0 Arg 1/0: None
id: 7 coverage: 0 Arg 1/0: None
id: 8 coverage: 0 Arg 1/0: None
id: 9 coverage: 0 Arg 1/0: None
id: 10 coverage: 0 Arg 1/0: None
id: 11 coverage: 0 Arg 1/0: None
id: 12 coverage: 0 Arg 1/0: None
id: 13 coverage: 0 Arg 1/0: None
id: 14 coverage: 0 Arg 1/0: None
id: 15 coverage: 0 Arg 1/0: None
id: 16 coverage: 0 Arg 1/0: None
id: 17 coverage: 0 Arg 1/0: None
id: 18 coverage: 0 Arg 1/0: None
id: 19 coverage: 0 Arg 1/0: None
id: 20 coverage: 0 Arg 1/0: None
id: 21 coverage: 0 Arg 1/0: None
id: 22 coverage: 0 Arg 1/0: None
id: 23 coverage: 0 Arg 1/0: None
id: 24 coverage: 0 Arg 1/0: None
id: 25 coverage: 0 Arg 1/0: None
id: 26 cover

In [ ]:
explainer.set_strategy('max_covi', 'universal')
## Define strategy before calling explainer.explain()
explainer.display_explanations()

0.40616693248272195
Number of extensions: 521076
len(max_cov_exts)= 12 / 521076
Covi strategy's coverage: 60
Top 5 covs: [58, 58, 58, 58, 58]
id: 0 coverage: 0 Arg 1/0: None
id: 1 coverage: 5 Arg 1/4: frozenset({'Relationship_Not-in-family', 'Occupation_Exec-managerial'})
id: 2 coverage: 0 Arg 1/0: None
id: 3 coverage: 3 Arg 1/1: frozenset({'Occupation_Machine-op-inspct', 'Age_28.00 < Age <= 37.00'})
id: 4 coverage: 0 Arg 1/0: None
id: 5 coverage: 2 Arg 1/1: frozenset({'Occupation_Farming-fishing', 'Age_28.00 < Age <= 37.00'})
id: 6 coverage: 2 Arg 1/1: frozenset({'Sex_Female', 'Occupation_Protective-serv'})
id: 7 coverage: 3 Arg 1/1: frozenset({'Occupation_Sales', 'Education_Bachelors'})
id: 8 coverage: 2 Arg 1/1: frozenset({'Occupation_?', 'Sex_Male'})
id: 9 coverage: 3 Arg 1/2: frozenset({'Occupation_Prof-specialty', 'Education_Bachelors', 'Workclass_Private'})
id: 10 coverage: 4 Arg 1/1: frozenset({'Occupation_Protective-serv', 'Sex_Male'})
id: 11 coverage: 1 Arg 1/1: frozenset({'A

In [ ]:
anchor_explainer = anchor_tabular.AnchorTabularExplainer(
    dataset.class_names,
    dataset.feature_names,
    dataset.train,
    dataset.categorical_names)
idx = 0
np.random.seed(1)
instance = dataset.train[idx].reshape(1, -1)[0]
print("Anchor")
print([dataset.categorical_names[i][int(r_)] for i, r_ in enumerate(instance)])

print('Prediction: ', anchor_explainer.class_names[c.predict(dataset.train[0].reshape(1, -1))[0]])
exp = anchor_explainer.explain_instance(dataset.train[idx], c.predict, threshold=0.95)
print('Anchor: %s' % (' AND '.join(exp.names())))
print('Precision: %.2f' % exp.precision())
print('Coverage: %.2f' % exp.coverage())

print("Arg:", idx)
print(explainer.explain_instance(idx))

Anchor
['Age > 48.00', 'Self-emp-not-inc', 'Some-college', 'Married-civ-spouse', 'Sales', 'Husband', 'White', 'Male', '2', '0', '40.00 < Hours per week <= 45.00', 'United-States']
Prediction:  b'>50K'
Anchor: Capital Gain = 2
Precision: 1.00
Coverage: 0.07
Arg: 0
id: 0 coverage: 10 Args5/5: {frozenset({'Occupation_Sales', 'Age_Age > 48.00'}), frozenset({'Workclass_Self-emp-not-inc', 'Age_Age > 48.00'}), frozenset({'Workclass_Self-emp-not-inc', 'Occupation_Sales'}), frozenset({'Education_Some-college', 'Workclass_Self-emp-not-inc'}), frozenset({'Education_Some-college', 'Occupation_Sales', 'Country_United-States'})}
None
